services:
  - type: pserv
    name: mysql
    plan: standard
    env: docker
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - fromGroup: mysql

envVarGroups:
  - name: mysql
    envVars:
      - key: MYSQL_DATABASE
        value: Env.get(DB_DATABASE)
      - key: MYSQL_USER
        value: Env.get(DB_USER)
      - key: MYSQL_PASSWORD
        value: Env.get(DB_PASSWORD)
        generateValue: true
